# Generated by Django 6.0 on 2025-12-10 02:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lugar', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=254)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('campo_imagen', models.ImageField(blank=True, null=True, upload_to='imagen_lugares/')),
                ('activo', models.BooleanField(default=True)),
                ('punt_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbbackend.categoria')),
            ],
            options={
                'verbose_name_plural': 'Lugares',
            },
        ),
    ]
